# Generated by Django 5.2 on 2025-04-08 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('COUNTRY', 'Country'), ('PROVINCE', 'Province'), ('DISTRICT', 'District'), ('SECTOR', 'Sector'), ('CELL', 'Cell'), ('VILLAGE', 'Village')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['location_id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.location')),
            ],
        ),
    ]
